### ISSUE TITLE
Where to download ground truth .bin file

### ISSUE THREAD

**Issue by wenyiwangbst** [TuSimple/SimpleTrack#7]
Hi, I download the validation_ground_truth_objects_gt.bin file from waymo but return error 
Traceback (most recent call last):
  File "gt_bin_decode.py", line 129, in <module>
    main(args.file_path, out_folder, args.data_folder)
  File "gt_bin_decode.py", line 81, in main
    segment_name = segment_name_list[val_index]
TypeError: list indices must be integers or slices, not NoneType
When I try to decode the ground truth .bin file

**Comment by ziqipang** [comment]
Close due to inactivity.
